# Generated by Django 3.0.5 on 2023-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=False, max_length=20, unique=True)),
                ('user_pw', models.CharField(default=False, max_length=256)),
                ('birth_day', models.DateField(null=True, verbose_name='생년월일')),
                ('gender', models.CharField(default='male', max_length=6, verbose_name='성별')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='이메일 주소')),
                ('name', models.CharField(default=False, max_length=20, verbose_name='이름')),
                ('age', models.IntegerField(default=20, verbose_name='나이')),
            ],
            options={
                'verbose_name': '로그인 테스트 테이블',
                'db_table': 'login_user',
            },
        ),
    ]
